[project]
name = "vllm-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepspeed>=0.18.2",
    "peft>=0.18.0",
    "scikit-learn>=1.7.2",
    "torch>=2.9.0",
    "trl>=0.25.1",
    "vllm>=0.11.2",
]
